version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962804699607.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t g4-c2-todo .
      - docker tag g4-c2-todo:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/g4-c2-todo:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/g4-c2-todo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"todo", "imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/g4-c2-todo:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json