version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t todo:v1 .
      - docker tag todo:v1 962804699607.dkr.ecr.us-west-2.amazonaws.com/g4-c2-todo:v1
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/g4-c2-todo:v1
      - echo Writing image definitions file...
      - printf '[{"name":"todo", "imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/g4-c2-todo:v1"}]' > imagedefinitions.json
artifacts:
  files: imagesdefinitions.json